name: Scale Model Kit
favicon: null
layout_spectrum: 0.8739109374582767
typography_spectrum: 0.5553866443224251
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.2590024818200618
  lightness: 0.47593230567872524
  saturation: 0.12908358708955348
  rhythmicContrast: 0.006660175276920199
purpose: []
