name: Scale Model Kit
favicon: null
layout_spectrum: 1
typography_spectrum: 0.31647
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#211e25'
    - '#06050a'
    - '#443a43'
    - '#84644e'
    - '#bd9677'
  brandStrength: 0.2590024818200618
  lightness: 0.47593230567872524
  saturation: 0.12908358708955348
  rhythmicContrast: 0.006660175276920199
purpose: []
